### ISSUE TITLE
打包后的dist bulid文件怎么处理？

### ISSUE THREAD

**Issue by MRuAyAN** [Orange2cat/alien_invasion#5]
有两个问题不是很理解。
1. 在打包的过程中，直接使用pyinstaller -F alien_invasion.py进行打包。打包后生成了build /dist文件夹，其中exe文件在dist文件夹中。你说需要将exe文件与images文件夹放在同一级目录下。我复制过去了，但是执行仍旧是无效的。这个是什么原因导致的呢？另外为什么你生成的exe文件，在没有build的情况下也能运行呢，而且你打包的exe文件比我的exe文件的大小足足大了一倍。
2. pyinstaller -D alien_invasion.py进行打包。打包后生成也一样生成build/dist文件夹，两个文件夹中均会有exe文件，且该exe文件的大小只有900k左右，没有发现有zip文件。该种打包方式生成zip文件错在什么地方呢？
希望楼主能解答一下，感谢。

**Comment by Orange2cat** [comment]
做了这些后，我一直用自己的私库了，所以不常上github。现在才看到，不好意思。就你所提的问题回答如下：
answer
1.---使用-F打包后的程序会将运行该文件所需要的所有文件，库等包含进去，但是不会包含外部引入文件（如图片），所以这个程序会很大。
---我们只需要dist文件夹的exe程序。其他的均可以删除。该程序是与images文件夹处于同一目录。
---你执行出错原因：a,打包出错，程序不完全；b，将exe程序放入images文件夹中了。要根据错误的提示找原因。
2.---我们所需要的文件是dist目录中的文件夹，这个文件夹包含了运行的环境（没有外部依赖文件）。
---我说明中指的zip文件是我github上上传的压缩包，该压缩包是正确的运行环境。不是你通过此次命令产生的。
附：打包后我们所需要的仅是dist目录的文件，built中的是构建过程中产生的文件，可以直接删了。
